plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
theme: jekyll-theme-minimal
title: emilybenjamin.com
description: emilybenjamin.com
show_downloads: false
